optimizer: {
  type: AdamW,
  kwargs: {
  lr: 0.001,
  weight_decay: 0.05}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 400,
    initial_epochs: 10}}

dataset: {
  train: { _base_: cfgs/dataset_configs/ModelNet40_linear_probing.yaml,
            others: {partition: 'train', num_points: 1024, subset: 'train'}},
  val: { _base_: cfgs/dataset_configs/ModelNet40_linear_probing.yaml,
            others: {partition: 'test', num_points: 1024, subset: 'test'}},
  test: { _base_: cfgs/dataset_configs/ModelNet40_linear_probing.yaml,
            others: {partition: 'test', num_points: 1024, subset: 'test'}}}
            
model : {
  NAME: PointTransformerMAE,
  trans_dim: 384,
  depth: 12,
  drop_path_rate: 0.1,
  cls_dim: 40,
  num_heads: 6,
  group_size: 32,
  num_group: 64,
  encoder_dims: 384,
}

total_bs: 128
step_per_update: 1
max_epoch: 300
